server:
  port: 8080
spring:
  application:
    name: ResourceServer
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
